name: dask-sql
channels:
- conda-forge
- nodefaults
dependencies:
- dask>=2022.3.0
# FIXME: handling is needed for httpx-based fastapi>=0.87.0
- fastapi>=0.69.0,<0.87.0
- fugue>=0.7.3
- intake>=0.6.0
- jsonschema
- libprotobuf=3
- lightgbm
- maturin>=0.12.8
- mlflow
- mock
# tpot imports fail with numpy >=1.24.0
# https://github.com/EpistasisLab/tpot/issues/1281
- numpy<1.24.0
- pandas>=1.4.0
- pre-commit
- prompt_toolkit>=3.0.8
- psycopg2
- pyarrow>=6.0.1
- pygments>=2.7.1
- pyhive
- pytest-cov
- pytest-rerunfailures
- pytest-xdist
- pytest
- python=3.10
- scikit-learn>=1.0.0
- setuptools-rust>=1.5.2
- sphinx
- sqlalchemy<2
- tpot
- tzlocal>=2.1
- uvicorn>=0.13.4
