name: dask-sql-docs
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - alabaster=0.7.12=py_0
  - alsa-lib=1.2.3=h516909a_0
  - attrs=20.2.0=pyh9f0ad1d_0
  - babel=2.8.0=py_0
  - bokeh=2.2.1=py38h32f6830_0
  - brotlipy=0.7.0=py38h1e0a361_1000
  - ca-certificates=2020.6.20=hecda079_0
  - cairo=1.16.0=h3fc0475_1005
  - certifi=2020.6.20=py38h32f6830_0
  - cffi=1.14.3=py38h5bae8af_0
  - chardet=3.0.4=py38h32f6830_1007
  - click=7.1.2=pyh9f0ad1d_0
  - cloudpickle=1.6.0=py_0
  - coverage=5.3=py38h1e0a361_0
  - cryptography=3.1.1=py38h766eaa4_0
  - cytoolz=0.11.0=py38h1e0a361_0
  - dask=2.28.0=py_0
  - dask-core=2.28.0=py_0
  - dask-sphinx-theme=1.3.2=pyh9f0ad1d_0
  - distributed=2.28.0=py38h32f6830_0
  - docutils=0.16=py38h32f6830_1
  - fontconfig=2.13.1=h1056068_1002
  - freetype=2.10.2=he06d7ca_0
  - fsspec=0.8.3=py_0
  - gettext=0.19.8.1=hc5be6a0_1002
  - giflib=5.2.1=h516909a_2
  - glib=2.66.1=h680cd38_0
  - graphite2=1.3.13=he1b5a44_1001
  - harfbuzz=2.7.2=hee91db6_0
  - heapdict=1.0.1=py_0
  - icu=67.1=he1b5a44_0
  - idna=2.10=pyh9f0ad1d_0
  - imagesize=1.2.0=py_0
  - iniconfig=1.0.1=pyh9f0ad1d_0
  - jinja2=2.11.2=pyh9f0ad1d_0
  - jpeg=9d=h516909a_0
  - jpype1=1.0.2=py38hbf85e49_0
  - lcms2=2.11=hbd6801e_0
  - ld_impl_linux-64=2.35=h769bd43_9
  - libblas=3.8.0=17_openblas
  - libcblas=3.8.0=17_openblas
  - libffi=3.2.1=he1b5a44_1007
  - libgcc-ng=9.3.0=h24d8f2e_16
  - libgfortran-ng=7.5.0=hdf63c60_16
  - libgomp=9.3.0=h24d8f2e_16
  - libiconv=1.16=h516909a_0
  - liblapack=3.8.0=17_openblas
  - libopenblas=0.3.10=pthreads_hb3c22a3_4
  - libpng=1.6.37=hed695b0_2
  - libstdcxx-ng=9.3.0=hdf63c60_16
  - libtiff=4.1.0=hc7e4089_6
  - libuuid=2.32.1=h14c3975_1000
  - libwebp-base=1.1.0=h516909a_3
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.10=h68273f3_2
  - locket=0.2.0=py_2
  - lz4-c=1.9.2=he1b5a44_3
  - markupsafe=1.1.1=py38h1e0a361_1
  - maven=3.6.0=0
  - more-itertools=8.5.0=py_0
  - msgpack-python=1.0.0=py38hbf85e49_1
  - ncurses=6.2=he1b5a44_1
  - numpy=1.19.1=py38hbc27379_2
  - olefile=0.46=py_0
  - openjdk=11.0.8=hacce0ff_0
  - openssl=1.1.1h=h516909a_0
  - packaging=20.4=pyh9f0ad1d_0
  - pandas=1.1.2=py38h950e882_0
  - partd=1.1.0=py_0
  - pcre=8.44=he1b5a44_0
  - pillow=7.2.0=py38h9776b28_1
  - pip=20.2.3=py_0
  - pixman=0.38.0=h516909a_1003
  - pluggy=0.13.1=py38h32f6830_2
  - psutil=5.7.2=py38h1e0a361_0
  - pthread-stubs=0.4=h14c3975_1001
  - py=1.9.0=pyh9f0ad1d_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pygments=2.7.1=py_0
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pysocks=1.7.1=py38h32f6830_1
  - pytest=6.1.0=py38h32f6830_0
  - pytest-cov=2.10.1=pyh9f0ad1d_0
  - python=3.8.5=h1103e12_9_cpython
  - python-dateutil=2.8.1=py_0
  - python_abi=3.8=1_cp38
  - pytz=2020.1=pyh9f0ad1d_0
  - pyyaml=5.3.1=py38h1e0a361_0
  - readline=8.0=he28a2e2_2
  - requests=2.24.0=pyh9f0ad1d_0
  - setuptools=49.6.0=py38h32f6830_1
  - six=1.15.0=pyh9f0ad1d_0
  - snowballstemmer=2.0.0=py_0
  - sortedcontainers=2.2.2=pyh9f0ad1d_0
  - sphinx=3.2.1=py_0
  - sphinx_rtd_theme=0.5.0=pyh9f0ad1d_0
  - sphinxcontrib-applehelp=1.0.2=py_0
  - sphinxcontrib-devhelp=1.0.2=py_0
  - sphinxcontrib-htmlhelp=1.0.3=py_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.3=py_0
  - sphinxcontrib-serializinghtml=1.1.4=py_0
  - sqlite=3.33.0=h4cf870e_0
  - tblib=1.6.0=py_0
  - tk=8.6.10=hed695b0_0
  - toml=0.10.1=pyh9f0ad1d_0
  - toolz=0.11.1=py_0
  - tornado=6.0.4=py38h1e0a361_1
  - typing_extensions=3.7.4.2=py_0
  - urllib3=1.25.10=py_0
  - wheel=0.35.1=pyh9f0ad1d_0
  - xorg-fixesproto=5.0=h14c3975_1002
  - xorg-inputproto=2.3.2=h14c3975_1002
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.12=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxfixes=5.0.3=h516909a_1004
  - xorg-libxi=1.7.10=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-libxtst=1.2.3=h516909a_1002
  - xorg-recordproto=1.14.2=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h516909a_0
  - zict=2.0.0=py_0
  - zlib=1.2.11=h516909a_1009
  - zstd=1.4.5=h6597ccf_2
  - pip:
    - adagio==0.2.2
    - antlr4-python3-runtime==4.9.1
    - appdirs==1.4.4
    - ciso8601==2.1.3
    - fs==2.4.12
    - fugue==0.5.0
    - pyarrow==2.0.0
    - qpd==0.2.5
    - sqlalchemy==1.3.22
    - triad==0.5.0
prefix: /home/nils/anaconda3/envs/dask-sql-docs
