name: Check for gpuCI updates

on:
  schedule:
    - cron: "0 0 * * *" # Daily “At 00:00” UTC
  workflow_dispatch:

jobs:
  update-gpuci:
    runs-on: ubuntu-latest
    if: github.repository == 'dask-contrib/dask-sql'

    steps:
      - uses: actions/checkout@v3

      - name: Parse current axis YAML
        id: rapids_current
        uses: the-coding-turtle/ga-yaml-parser@v0.1.2
        with:
          file: continuous_integration/gpuci/axis.yaml

      - name: Get latest cuDF nightly version
        id: cudf_latest
        uses: jacobtomlinson/gha-anaconda-package-version@0.1.3
        with:
          org: "rapidsai-nightly"
          package: "cudf"
          version_system: "CalVer"

      - name: Get latest cuML nightly version
        id: cuml_latest
        uses: jacobtomlinson/gha-anaconda-package-version@0.1.3
        with:
          org: "rapidsai-nightly"
          package: "cuml"
          version_system: "CalVer"

      - name: Get latest UCX-Py nightly version
        id: ucx_py_latest
        uses: jacobtomlinson/gha-anaconda-package-version@0.1.3
        with:
          org: "rapidsai-nightly"
          package: "ucx-py"
          version_system: "CalVer"

      - name: Get old RAPIDS / UCX-Py versions
        env:
          FULL_CUDF_VER: ${{ steps.cudf_latest.outputs.version }}
          FULL_CUML_VER: ${{ steps.cuml_latest.outputs.version }}
          FULL_UCX_PY_VER: ${{ steps.ucx_py_latest.outputs.version }}
        run: |
          echo RAPIDS_VER=${{ steps.rapids_current.outputs.RAPIDS_VER_0 }} >> $GITHUB_ENV
          echo UCX_PY_VER=$(curl -sL https://version.gpuci.io/rapids/${{ steps.rapids_current.outputs.RAPIDS_VER_0 }}) >> $GITHUB_ENV
          echo NEW_CUDF_VER=${FULL_CUDF_VER::-10} >> $GITHUB_ENV
          echo NEW_CUML_VER=${FULL_CUML_VER::-10} >> $GITHUB_ENV
          echo NEW_UCX_PY_VER=${FULL_UCX_PY_VER::-10} >> $GITHUB_ENV

      - name: Update RAPIDS version
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          include: 'continuous_integration/gpuci/**'
          find: "${{ env.RAPIDS_VER }}"
          replace: "${{ env.NEW_CUDF_VER }}"
          regex: true

      - name: Update UCX-Py version
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          include: 'continuous_integration/gpuci/**'
          find: "${{ env.UCX_PY_VER }}"
          replace: "${{ env.NEW_UCX_PY_VER }}"
          regex: true

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        # make sure ucx-py nightlies are available and that cuDF/cuML nightly versions match up
        if: |
          env.UCX_PY_VER != env.NEW_UCX_PY_VER &&
          env.RAPIDS_VER != env.NEW_CUDF_VER &&
          env.NEW_CUDF_VER == env.NEW_CUML_VER
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          commit-message: "Update gpuCI `RAPIDS_VER` to `${{ env.NEW_CUDF_VER }}`"
          title: "Update gpuCI `RAPIDS_VER` to `${{ env.NEW_CUDF_VER }}`"
          team-reviewers: "dask/gpu"
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          branch: "upgrade-gpuci-rapids"
          body: |
            New cuDF and ucx-py nightly versions have been detected.

            Updated gpuCI to use RAPIDS ${{ env.NEW_CUDF_VER }} and UCX-Py ${{ env.NEW_UCX_PY_VER }}.
